apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tax-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dekee/tracker.git
    targetRevision: main
    path: k8s/overlays/kind
  destination:
    server: https://kubernetes.default.svc
    namespace: tax-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

