apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: tax-tracker-parcels
    namespace: tax-tracker
    files:
      - parcels.txt=parcels.txt

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - app-deployment.yaml
  - app-service.yaml

