apiVersion: v1
kind: Service
metadata:
  name: tax-tracker-postgres
  namespace: tax-tracker
spec:
  selector:
    app: tax-tracker-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

