apiVersion: v1
kind: Secret
metadata:
  name: tax-tracker-postgres
  namespace: tax-tracker
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: tasktracker

